# Generated by Django 3.0.7 on 2024-03-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_supplier_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='perprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
