# Generated by Django 3.0.7 on 2024-03-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240316_0741'),
        ('transactions', '0003_auto_20240318_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='inventory.Stock'),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='billno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedetailsbillno', to='transactions.PurchaseBill'),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='billno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saledetailsbillno', to='transactions.SaleBill'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
