# Generated by Django 3.0.7 on 2024-03-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240326_1051'),
        ('transactions', '0005_auto_20240318_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='billno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedetailsbillno', to='transactions.PurchaseBill'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='billno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitems', to='transactions.PurchaseBill'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitems', to='inventory.Stock'),
        ),
    ]
