# Generated by Django 3.0.7 on 2024-03-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240326_1051'),
        ('transactions', '0006_auto_20240326_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Stock')),
            ],
        ),
    ]
