# Generated by Django 3.0.7 on 2024-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20240330_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
