# Generated by Django 3.0.7 on 2024-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_cartitem_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
