# Generated by Django 3.0.7 on 2024-04-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20240403_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
