# Generated by Django 3.0.7 on 2024-04-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20240407_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
