# Generated by Django 3.0.7 on 2024-04-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20240415_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebilldetails',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=50, null=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salepayments', to='transactions.SaleBill')),
            ],
        ),
    ]
