# Generated by Django 3.0.7 on 2024-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20240415_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepayment',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='salepayment',
            name='payment_details',
            field=models.TextField(default='{}'),
        ),
    ]
