# Generated by Django 3.0.7 on 2024-03-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='product',
        ),
    ]
